# Generated by Django 3.0.8 on 2020-09-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to='processing/')),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='flaggedRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='infoFieldCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='negativeTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negterm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='positiveTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='processingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('softwarename', models.CharField(max_length=30)),
                ('publishername', models.CharField(blank=True, max_length=50, null=True)),
                ('informationpage', models.CharField(blank=True, max_length=50, null=True)),
                ('restrictionlist', models.TextField(blank=True, null=True)),
                ('fulldoctext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='restrictionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='restrictionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrictionterm', models.CharField(max_length=20)),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.restrictionTitle')),
            ],
        ),
        migrations.CreateModel(
            name='infoFieldArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listvalue', models.CharField(max_length=50)),
                ('categoryname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processing.infoFieldCategory')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.processingData')),
            ],
        ),
        migrations.CreateModel(
            name='flaggedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.flaggedRestriction')),
            ],
        ),
        migrations.AddField(
            model_name='flaggedrestriction',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.processingData'),
        ),
    ]
