# Generated by Django 3.0.8 on 2020-10-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_flaggedsentence_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedrestriction',
            name='flaggedcolor',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
