# Generated by Django 3.0.8 on 2020-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='softwareIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwarename', models.CharField(max_length=30)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('publishername', models.CharField(blank=True, max_length=30, null=True)),
                ('informationurl', models.CharField(blank=True, max_length=50, null=True)),
                ('flaggedrestrictions', models.TextField(blank=True, null=True)),
                ('storeddocument', models.TextField(blank=True, null=True)),
                ('checkdate', models.DateTimeField(blank=True, null=True)),
                ('checkby', models.CharField(blank=True, max_length=50, null=True)),
                ('licensetype', models.CharField(blank=True, max_length=30, null=True)),
                ('licensecount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
