# Generated by Django 3.0.8 on 2020-10-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_flaggedrestriction_flaggedcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictiontitle',
            name='postname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
