# Generated by Django 3.0.8 on 2020-11-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_softwareindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingdata',
            name='parentsoftware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.softwareIndex'),
        ),
    ]
