# Generated by Django 3.0.8 on 2020-11-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_processingdata_parentsoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingdata',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
