# Generated by Django 3.0.8 on 2020-11-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareindex',
            name='licensecount',
        ),
        migrations.RemoveField(
            model_name='softwareindex',
            name='licensetype',
        ),
        migrations.RemoveField(
            model_name='softwareindex',
            name='storeddocument',
        ),
        migrations.RemoveField(
            model_name='softwareindex',
            name='version',
        ),
    ]
