# Generated by Django 3.0.8 on 2020-11-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201105_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='softwareIndex',
        ),
    ]
